### ISSUE TITLE
Customizable Format for Items in Chest GUI

### ISSUE THREAD

**Issue by vancorl** [Simplexity-Development/SimplePrefixes#5]
Prefix customization lacks \n for line break, because not all parameters can be changed.... For example, it would be better to make a placeholder with the status of the prefix, whether it is available or not, e.g.
%available%

**Comment by Peashooter101** [comment]
@vancorl This issue is unclear. I do not understand what you are asking for.

Please provide an example or explain further what you are asking for.

**Comment by vancorl** [comment]
Hi. 
When is the new version coming out?
